let SENDGRID_KEYS = {
  SENDGRID_API_KEY: 'SET UP YOUR OWN',
  myEmailAddres: 'Set up your own',
};
let MONGODB_KEYS = {
  user: 'SET UP YOUR OWN',
  password: 'SET UP YOUR OWN',
};
let STRIPE_KEY = {
  STRIPE_PUBLIC_KEY: 'SET UP YOUR OWN',
  STRIPE_SECRET_KEY: 'SET UP YOUR OWN',
};

exports.MONGODB_KEYS = MONGODB_KEYS;
exports.SENDGRID_KEYS = SENDGRID_KEYS;
exports.STRIPE_KEY = STRIPE_KEY;
